// Code generated by "stringer -type=DNSType"; DO NOT EDIT.

package dns

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Query-0]
	_ = x[Response-1]
}

const _DNSType_name = "QueryResponse"

var _DNSType_index = [...]uint8{0, 5, 13}

func (i DNSType) String() string {
	if i >= DNSType(len(_DNSType_index)-1) {
		return "DNSType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _DNSType_name[_DNSType_index[i]:_DNSType_index[i+1]]
}
