// Code generated by "stringer -type=QueryClass"; DO NOT EDIT.

package dns

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[IN-1]
	_ = x[CS-2]
	_ = x[CH-3]
	_ = x[HS-4]
	_ = x[ANY_CLASS-255]
}

const (
	_QueryClass_name_0 = "INCSCHHS"
	_QueryClass_name_1 = "ANY_CLASS"
)

var (
	_QueryClass_index_0 = [...]uint8{0, 2, 4, 6, 8}
)

func (i QueryClass) String() string {
	switch {
	case 1 <= i && i <= 4:
		i -= 1
		return _QueryClass_name_0[_QueryClass_index_0[i]:_QueryClass_index_0[i+1]]
	case i == 255:
		return _QueryClass_name_1
	default:
		return "QueryClass(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
