// Code generated by "stringer -type=QueryType"; DO NOT EDIT.

package dns

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[A-1]
	_ = x[NS-2]
	_ = x[MD-3]
	_ = x[MF-4]
	_ = x[CNAME-5]
	_ = x[SOA-6]
	_ = x[MB-7]
	_ = x[MG-8]
	_ = x[MR-9]
	_ = x[NULL-10]
	_ = x[WKS-11]
	_ = x[PTR-12]
	_ = x[HINFO-13]
	_ = x[MINFO-14]
	_ = x[MX-15]
	_ = x[TXT-16]
	_ = x[AAAA-28]
	_ = x[AXFR-252]
	_ = x[MAILB-253]
	_ = x[MAILA-254]
	_ = x[ANY_QUERY-255]
}

const (
	_QueryType_name_0 = "ANSMDMFCNAMESOAMBMGMRNULLWKSPTRHINFOMINFOMXTXT"
	_QueryType_name_1 = "AAAA"
	_QueryType_name_2 = "AXFRMAILBMAILAANY_QUERY"
)

var (
	_QueryType_index_0 = [...]uint8{0, 1, 3, 5, 7, 12, 15, 17, 19, 21, 25, 28, 31, 36, 41, 43, 46}
	_QueryType_index_2 = [...]uint8{0, 4, 9, 14, 23}
)

func (i QueryType) String() string {
	switch {
	case 1 <= i && i <= 16:
		i -= 1
		return _QueryType_name_0[_QueryType_index_0[i]:_QueryType_index_0[i+1]]
	case i == 28:
		return _QueryType_name_1
	case 252 <= i && i <= 255:
		i -= 252
		return _QueryType_name_2[_QueryType_index_2[i]:_QueryType_index_2[i+1]]
	default:
		return "QueryType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
