// Code generated by "stringer -type=ResponseCode"; DO NOT EDIT.

package dns

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[NoError-0]
	_ = x[FormatError-1]
	_ = x[ServerFailure-2]
	_ = x[NameError-3]
	_ = x[NotImplemented-4]
	_ = x[Refused-5]
}

const _ResponseCode_name = "NoErrorFormatErrorServerFailureNameErrorNotImplementedRefused"

var _ResponseCode_index = [...]uint8{0, 7, 18, 31, 40, 54, 61}

func (i ResponseCode) String() string {
	if i >= ResponseCode(len(_ResponseCode_index)-1) {
		return "ResponseCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _ResponseCode_name[_ResponseCode_index[i]:_ResponseCode_index[i+1]]
}
